name: Generate test compilation artifacts

env:
  RISCV_TESTS_REPO: https://github.com/riscv-software-src/riscv-tests.git
  RISCV_TESTS_REV: master
  TOOLCHAIN_URL: https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v12.2.0-1/xpack-riscv-none-elf-gcc-12.2.0-1-linux-x64.tar.gz
  RISCV: /opt/riscv/toolchain

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    name: Test debug (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler build-essential

      - name: Get the toolchain from cache (if available)
        id: cache-restore-toolchain
        uses: actions/cache/restore@v3
        with:
          path: /opt/riscv/toolchain
          key: "toolchain-${{env.TOOLCHAIN_URL}}"

      - if: ${{ steps.cache-restore-toolchain.outputs.cache-hit != 'true' }}
        name: Download Toolchain (if not cached)
        run: |
          mkdir -p /opt/riscv/toolchain
          wget --progress=dot:giga $TOOLCHAIN_URL -O /tmp/toolchain.tar.gz

      - if: ${{ steps.cache-restore-toolchain.outputs.cache-hit != 'true' }}
        name: Install Toolchain (if not cached)
        run: tar zxf /tmp/toolchain.tar.gz --strip-components=1 -C /opt/riscv/toolchain

      - name: Save the toolchain to the cache (if necessary)
        id: cache-save-toolchain
        uses: actions/cache/save@v3
        with:
          path: /opt/riscv/toolchain
          key: "toolchain-${{env.TOOLCHAIN_URL}}"
          
      - name: 'Exporting RISCV Variable'    
        run: |
           echo "riscv variable: $RISCV"
           echo "${{ env.RISCV }}" >> $GITHUB_PATH
           echo "${{ env.RISCV }}/bin" >> $GITHUB_PATH
      
      - name: "Show folder structure"
        run: ls -lah

      - name: "Building from repository"
        run: |
           autoconf
           ./configure --prefix=$RISCV/target
           make
           make install

      - name: Archive test logs
        # Proceed even if there was a failed test
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: riscv-tests/debug/logs
