name: Generate test compilation artifacts

env:
  RISCV_TESTS_REPO: https://github.com/riscv-software-src/riscv-tests.git
  RISCV_TESTS_REV: master
  TOOLCHAIN_URL: https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v12.2.0-1/xpack-riscv-none-elf-gcc-12.2.0-1-linux-x64.tar.gz
  RISCV: /opt/riscv/toolchain

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  test:
    name: Test debug (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler build-essential  gcc-riscv64-unknown-elf
  
      - name: "Show config"
        run: |
           ls -lah
           echo "riscv variable: $RISCV"

      - name: "Building from repository"
        run: |
           autoconf
           ./configure --prefix=$RISCV/target
           make
           make install

      - name: Archive test logs
        # Proceed even if there was a failed test
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: riscv-tests/debug/logs
